const USERS_DATA = [
  {
    PK: 'USER#1',
    SK: 'NAME#Kobe Bryant',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '1',
    name: 'Kobe Bryant',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#2',
    SK: 'NAME#Lebron James',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '2',
    name: 'Lebron James',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#3',
    SK: 'NAME#Stephen Curry',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '3',
    name: 'Stephen Curry',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#4',
    SK: 'NAME#Kevin Durant',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '4',
    name: 'Kevin Durant',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#5',
    SK: 'NAME#James Harden',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '5',
    name: 'James Harden',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#6',
    SK: 'NAME#Draymond Green',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '6',
    name: 'Draymond Green',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#7',
    SK: 'NAME#Klay Thompson',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '7',
    name: 'Klay Thompson',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#8',
    SK: 'NAME#Anthony Davis',
    GSI1: 'CATEGORY#NBA',
    LSI1: 'ROLE#Player',
    id: '8',
    name: 'Anthony Davis',
    category: 'NBA',
    role: 'Player',
  },
  {
    PK: 'USER#9',
    SK: 'NAME#Messi',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '9',
    name: 'Messi',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#10',
    SK: 'NAME#Ronaldo',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '10',
    name: 'Ronaldo',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#11',
    SK: 'NAME#Neymar',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '11',
    name: 'Neymar',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#12',
    SK: 'NAME#Cristiano',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '12',
    name: 'Cristiano',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#13',
    SK: 'NAME#Lukaku',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '13',
    name: 'Lukaku',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#14',
    SK: 'NAME#Kante',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '14',
    name: 'Kante',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#15',
    SK: 'NAME#Kroos',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '15',
    name: 'Kroos',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#16',
    SK: 'NAME#Modric',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '16',
    name: 'Modric',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#17',
    SK: 'NAME#Bale',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '17',
    name: 'Bale',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#18',
    SK: 'NAME#Benzema',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '18',
    name: 'Benzema',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#19',
    SK: 'NAME#Griezmann',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '19',
    name: 'Griezmann',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#20',
    SK: 'NAME#Puyol',
    GSI1: 'CATEGORY#Soccer',
    LSI1: 'ROLE#Player',
    id: '20',
    name: 'Puyol',
    category: 'Soccer',
    role: 'Player',
  },
  {
    PK: 'USER#21',
    SK: 'NAME#Bradley Wiggins',
    GSI1: 'CATEGORY#Cycling',
    LSI1: 'ROLE#Rider',
    id: '21',
    name: 'Bradley Wiggins',
    category: 'Cycling',
    role: 'Rider',
  },
  {
    PK: 'USER#22',
    SK: 'NAME#Jenson Button',
    GSI1: 'CATEGORY#Cycling',
    LSI1: 'ROLE#Rider',
    id: '22',
    name: 'Jenson Button',
    category: 'Cycling',
    role: 'Rider',
  },
  {
    PK: 'USER#22',
    SK: 'NAME#Spongebob',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '22',
    name: 'Spongebob',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#23',
    SK: 'NAME#Patrick',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '23',
    name: 'Patrick',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#24',
    SK: 'NAME#Squidward',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '24',
    name: 'Squidward',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#25',
    SK: 'NAME#Mr. Krabs',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '25',
    name: 'Mr. Krabs',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#26',
    SK: 'NAME#Gary',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '26',
    name: 'Gary',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#27',
    SK: 'NAME#Larry',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '27',
    name: 'Larry',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#28',
    SK: 'NAME#Sandy',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '28',
    name: 'Sandy',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#29',
    SK: 'NAME#Plankton',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '29',
    name: 'Plankton',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#30',
    SK: 'NAME#Sonic',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '30',
    name: 'Sonic',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#31',
    SK: 'NAME#Tails',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '31',
    name: 'Tails',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#32',
    SK: 'NAME#Knuckles',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '32',
    name: 'Knuckles',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#33',
    SK: 'NAME#Rouge',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '33',
    name: 'Rouge',
    category: 'TV',
    role: 'Character',
  },
  {
    PK: 'USER#34',
    SK: 'NAME#Chaos',
    GSI1: 'CATEGORY#TV',
    LSI1: 'ROLE#Character',
    id: '34',
    name: 'Chaos',
    category: 'TV',
    role: 'Character',
  },
];

module.exports = {
  USERS_DATA,
};
