const DATA_TRANSFORMATIONS_FOLDER_NAME = 'data-transformations';
const BASE_TRANSFORMATIONS_FOLDER_PATH = `${process.cwd()}/${DATA_TRANSFORMATIONS_FOLDER_NAME}`;
const TRANSFORMATION_SCRIPT_EXTENSION = '.js';
const TRANSFORMATION_NUMBER_PREFIX = 'v';
const TRANSFORMATION_NAME_SEPARATOR = '_';

const DATA_TRANSFORMATIONS_KEY_ID = 'DataTransformations';

module.exports = {
  DATA_TRANSFORMATIONS_FOLDER_NAME,
  BASE_TRANSFORMATIONS_FOLDER_PATH,
  TRANSFORMATION_SCRIPT_EXTENSION,
  TRANSFORMATION_NUMBER_PREFIX,
  TRANSFORMATION_NAME_SEPARATOR,
  DATA_TRANSFORMATIONS_KEY_ID,
};
