const DATA_MIGRATIONS_FOLDER_NAME = 'data-migrations';
const BASE_MIGRATIONS_FOLDER_PATH = `${process.cwd()}/${DATA_MIGRATIONS_FOLDER_NAME}`;
const MIGRATION_SCRIPT_EXTENSION = '.js';
const MIGRATION_NUMBER_PREFIX = 'v';
const MIGRATION_NAME_SEPARATOR = '_';

const DATA_MIGRATIONS_KEY_ID = 'DataMigrations';

module.exports = {
  DATA_MIGRATIONS_FOLDER_NAME,
  BASE_MIGRATIONS_FOLDER_PATH,
  MIGRATION_SCRIPT_EXTENSION,
  MIGRATION_NUMBER_PREFIX,
  MIGRATION_NAME_SEPARATOR,
  DATA_MIGRATIONS_KEY_ID,
};
